name: Daily Commit

on:
  schedule:    
    - cron:  '0 0 * * *'      
  workflow_dispatch:
  
jobs:
  commit:    
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actor
